Header and headeline  for mobile version
souad988/Portfolio pull request #2
Opened 2022-01-06 14:02 UTC by souad988

created header with welcome and menu icon 
created headline section with headline and description 
added socialmedia icons

2022-01-06 15:03 UTC, ReshyResh requested changes
# Hi @souad988 , 

### You did a really good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

To highlight:
  - ✔ Meaningful commit messages.
  - ✔ All content is aligned with flexbox.


## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### None.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 08:12 UTC, Whoistolu requested changes
Hi @souad988 ,

Good job so far!
Thank you for implementing some of the recommended changes by the last reviewer however, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] [OPTIONAL] Kindly ensure that the first letter of your commit message starts with a capital letter. This is will groom your into writing professional commit messages. See bellow:
### Your commit messages
![your-commit-message](https://user-images.githubusercontent.com/58692590/148511160-7ce5f610-de02-40bc-a4a8-a72e7ab9a0b3.png)

### Standard Commit Message Template
![proper-commit-messages](https://user-images.githubusercontent.com/58692590/148511232-b0781c45-0b61-48ba-94dc-0e5e553b4268.png)



_Please check the inline comments under the review for sections to improve._

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-07 08:12 UTC, Whoistolu commented on src/index.html
> +                </div>
- [ ] [REQUIRED] It is nice to see that you have embedded the icons in an unordered and ordered list, however, the link to the icons are broken as they do not display on your page. Please refer to the design images above for proper clarity,

2022-01-07 08:21 UTC, Whoistolu commented on src/index.html
> +           <div class="social_media">
- [ ] [REQUIRED] It is nice to see that you have implemented the unordered list and the ordered list however, the social media icons do not display. Please refer to this [comments](https://github.com/souad988/Portfolio/pull/2#pullrequestreview-846348945) for more clarity.

2022-01-07 10:47 UTC, FrederickMih approved these changes
# Hi @souad988 , 

#### NB.  As a reminder, please add a descriptive README file for this project. Your README file is the first impression a visitor takes about your project. It will be nice to make it more descriptive and professional. You should use [this template](https://github.com/microverseinc/readme-template) and later customize it for your project.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-07 10:47 UTC, FrederickMih commented on src/index.html
> +                            <h1 class="headline-1">Hey there. I’m Souad</h1>
- Hi @souad988, great job for making these changes

2022-01-07 10:47 UTC, FrederickMih commented on src/index.html
> +                                <li><a href="https://www.angellist.com/"><img src="../media/icons/angellist.png" alt="angellist"/></a></li>
- Great job for fixing this issue addressed by the previous reviewers.

2022-01-07 10:53 UTC, merged